### PR TITLE
fixed sysctl test

### PR DESCRIPTION
**Pull request by lil-cain**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi again, I have similar questions about this commit as I did about #157 :-) The code looks almost unchanged, so is this fixing a test failure or is it merely refactoring the code?

**Comment by lil-cain** [comment]
It's fixing a test failure.

**Comment by mgeisler** [comment]
Okay, I also find the new code easier to read and better in that regard.

I'm not the owner of this project, so my opinion is just that, an opinion :-) I once wrote down what I would like to see in a [good commit message][1] and that might help explain the reasoning behind my many questions :-) That was for an unrelated project, but it's a mix of other guides I've seen used by different open source projects.

[1]: http://docs.zerovm.org/contributing.html#commit-messages

**Comment by lil-cain** [comment]
Closing as included in #158

**Pull request closed without merging**
