### PR TITLE
fixed rackconnect test

### PR DESCRIPTION
**Pull request by lil-cain**

### CODE REVIEW

**Comment by mgeisler** [comment]
Hi Cian, I'm just thinking aloud here to explain the kind of questions that run through my head when I see this pull request.

Could you expand on why this change is necessary? What was the (wrong) behavior you were seeing before?

Without knowing Ruby that well, I see the code drilling down in the `OHAI` variable and accessing `'rackspace'`, `'rackconnect'`, and `'enabled'` keys. That seems to have been left the same, though you removed the (unnecessary, I guess?) `rackspace` variable.

The real change seems to be changing `.to exist` to `.not_to be_nil`. What is the difference between the two and why did the old code not work?

**Comment by lil-cain** [comment]
It's fixing a broken test. Currently `OHAI['rackspace']['rackconnect']['enabled']` is `false` in ruby. `false` doesn't have an `exist?` method defined, so this test fails.

**Comment by mgeisler** [comment]
Okay, thanks. I would love to see something like this in the commit message in the future!

**Comment by lil-cain** [comment]
Closing this PR, as included in PR #158

**Pull request closed without merging**
